Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 625, in __str__
    return self._str
AttributeError: 'PosixPath' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rokey/1_ws/src/my_video_package/setup.py", line 7, in <module>
    setup(
  File "/home/rokey/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/rokey/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 170, in setup
    ok = dist.parse_command_line()
  File "/home/rokey/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 472, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/home/rokey/.local/lib/python3.10/site-packages/setuptools/dist.py", line 901, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/home/rokey/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 531, in _parse_command_opts
    cmd_class = self.get_command_class(command)
  File "/home/rokey/.local/lib/python3.10/site-packages/setuptools/dist.py", line 742, in get_command_class
    eps = metadata.entry_points(group='distutils.commands', name=command)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1019, in <genexpr>
    dist.entry_points for dist in unique(distributions())
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 631, in entry_points
    return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 927, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
  File "/usr/lib/python3.10/pathlib.py", line 632, in __fspath__
    return str(self)
  File "/usr/lib/python3.10/pathlib.py", line 625, in __str__
    return self._str
KeyboardInterrupt
